config/routes.rb
Rails.application.routes.draw do
  root "html_pages#home"
  get "/help", to: "html_pages#help"
  get "/about", to: "html_pages#about"
  get "/contact", to: "html_pages#contact"
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users
  resources :snapshots, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snapshot.rb
class Snapshot < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }

  validates :image, content_type: { in: %w[image/jpeg image/gif image/png image/webp], message: "Please upload a valid file type (jpeg, gif, png or webp)." },
                    size: { less_than: 5.megabytes, message: "Your image exceeds 5MB." }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :snapshots, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 60 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 60 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def feed
    Snapshot.where("user_id = ?", id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in"
      redirect_to login_url
    end
  end
end

app/controllers/html_pages_controller.rb
class HtmlPagesController < ApplicationController
  def home
    if logged_in?
      @snapshot = current_user.snapshots.build if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = "Invalid email/password combination"
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/snapshots_controller.rb
class SnapshotsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: :destroy

  def create
    @snapshot = current_user.snapshots.build(snapshot_params)
    @snapshot.image.attach(params[:snapshot][:image])
    if @snapshot.save
      flash[:success] = "Snapshot created"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render "html_pages/home"
    end
  end

  def destroy
    @snapshot.destroy
    flash[:success] = "Snapshot has been deleted."
    redirect_to request.referrer || root_url
  end

  private

  def snapshot_params
    params.require(:snapshot).permit(:content, :image)
  end

  def correct_user
    @snapshot = current_user.snapshots.find_by(id: params[:id])
    redirect_to root_url if @snapshot.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @snapshots = @user.snapshots.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to Orbit!"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns a full title on a per page basis

  #Method definition, optional argument
  def full_title(page_title = "")
    #Creating and assigning a variable
    base_title = "Orbit Feedback Application"
    # Boolean test
    if page_title.empty?
      #Implicit return
      base_title
    else
      #String concatenation
      page_title + " | " + base_title
    end
  end
end

app/helpers/html_pages_helper.rb
module HtmlPagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

  def current_user?(user)
    user && user == current_user
  end
end

app/helpers/snapshots_helper.rb
module SnapshotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/html_pages/about.html.erb
<% provide(:title, "About") %>

<h1>Orbit <%= yield(:title) %> Page</h1>
<p>This is the template <b><%= yield(:title) %> Page</b> for out Orbit Feedback Application</p>

app/views/html_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

app/views/html_pages/help.html.erb
<% provide(:title, "Help") %>

<h1>Orbit <%= yield(:title) %> Page</h1>
<p>This is the template <b><%= yield(:title) %> Page</b> for out Orbit Feedback Application</p>

app/views/html_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>      
      </section>
      <section class="snapshot_form">
        <%= render "shared/snapshot_form" %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Snapshot Feed</h3>
      <%= render "shared/feed" %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to Orbit</h1>
    <h2>
      This is the homepage of the Orbit application. You can find the codebase for this application at 
      <a href="https://github.com/lucas-andrade94/ruby-orbit">my GitHub</a>.
    </h2>

    <%= link_to "Create an account", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Orbit Feedback Application
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Orbit Application", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a  href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
            </ul>
          </li>
          <% else %>
            <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html 5.min.js">
  </script>
<![endif]>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do | message_type, message | %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>
          <%= msg %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="snapshots">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, params: { controller: :html_pages, action: :home } %>
<% end %>

app/views/shared/_snapshot_form.html.erb
<%= form_with(model: @snapshot, local: true) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Create a new snapshot..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="image">
    <%= f.file_field :image, accept: "image/jpeg, image/gif, image/png, image/webp" %>
  </span>
<% end %>

<script type="text/javascript">
  $("#snapshot_image").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Image cannot exceed 5MB. Please choose a smaller file.");
    }
    $("#snapshot_image").val("");
  });
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.snapshots.count, "snapshot") %></span>

app/views/snapshots/_snapshot.html.erb
<li id="snapshot-<%= snapshot.id %>">
  <%= link_to gravatar_for(snapshot.user, size: 50), snapshot.user %>
  <span class="user"><%= link_to snapshot.user.name, snapshot.user %></span>
  <span class="content"><%= snapshot.content %></span>
  <%= image_tag snapshot.image if snapshot.image.attached? %>
  <span class="timestamp">
    Posted <%= time_ago_in_words(snapshot.created_at) %> ago.
    <% if current_user?(snapshot.user) %>
      <%= link_to "delete", snapshot, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </span>
</li>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "Are you sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="https://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "All Users") %>
<h1>All Users</h1>

<%= will_paginate %>

<ul class="users">  
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>

<h1>Signup</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.snapshots.any? %>
      <h3>Snapshots <%= @user.snapshots.count %></h3>
      <ol class="snapshots">
        <%= render @snapshots %>
      </ol>
      <%= will_paginate @snapshots %>
    <% end %>
  </div>
</div>